version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=ADMIN
      - POSTGRES_PASSWORD=ADMIN
      - POSTGRES_DB=DATABASE
  reservas:
    build: .
    ports:
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    