import Head from 'next/head'
import React, { useEffect } from 'react';
import { signIn, signOut } from 'next-auth/react';
import Button from '@components/Button';
import ItemRegisterUser from '@components/ItemRegisterUser';

const Home = () => {

  return (
    <div >
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='bg-red-800'>Hola</div>
    <Button onClick={() => {
      signIn('google')
    }} text="Iniciar" isSubmit={false}/>

<button onClick={() => {
      signOut('google')
    }}> salir</button>

<ItemRegisterUser email="Santiagomarinocapo" />
  </div>
  );
};

export default Home;
