import Head from 'next/head'
import React, { useEffect } from 'react';
import { gql, useQuery } from '@apollo/client'
import { signIn } from 'next-auth/react';

const get= gql ` 
query ExampleQuery {
  prueba
}`
const Home = () => {
  const {data} = useQuery(get);

  useEffect(()=>{
     console.log(data)
  }, [data])
  return (
    <div >
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='bg-red-800'>Hola</div>
    <button onClick={() => {
      signIn('google')
    }}> Iniciar</button>

  </div>
  );
};

export default Home;
